### ISSUE TITLE
error launching

### ISSUE THREAD

**Issue by Paura7** [Beelzebub2/AutoBanana#1]
Starting AutoBanana...
  File "C:\Users\xxx\Downloads\AutoBanana-main\AutoBanana.py", line 47
    print(f"{Fore.YELLOW}{
          ^
SyntaxError: unterminated string literal (detected at line 47)

**Comment by Beelzebub2** [comment]
Should be fixed now

**Comment by SavageCore** [comment]
Fixed it with #5
