### ISSUE TITLE
Why does it access every game file?

### ISSUE THREAD

**Issue by Roki100** [Beelzebub2/AutoBanana#14]
Hi! I ran the executable and started analysing its behavior for security reasons and it seems to start accessing game files of every single game i have installed, what is that caused by, what is it for?

**Comment by Beelzebub2** [comment]
Pretty simple actually it searches all steam games and checks wich ones are in the config file so it knows what executables to close although i my self didn't do that part it was a contributor of the project

**Comment by Beelzebub2** [comment]
Pretty simple actually it searches all steam games and checks wich ones are in the config file so it knows what executables to close although i my self didn't do that part it was a contributor of the project 

The function that does that is in line 164

**Comment by Roki100** [comment]
ah okay, it would be great to have an option to disable this behavior somehow as this particular feature makes the entire thing not work on my end due to the amount of games i have installed i guess, its just stuck and scans games one by one for long long time until i lose my patience

**Comment by Beelzebub2** [comment]
Wait do you get any errors? Does it print the text Autobanana? What's behavior

**Comment by Roki100** [comment]
> Wait do you get any errors? Does it print the text Autobanana? What's behavior

no errors, no text printed, its just stuck and when i checked deeply on what it does it just scans every single game file of every game i have installed

it also refused to run on a different drive than C as it couldnt move logo.txt to "another drive" aka appdata which is on C

**Comment by Beelzebub2** [comment]
Im sorry you had that problem i will look into it when i get home

**Comment by Beelzebub2** [comment]
Alright should be fixed now @Roki100

**Comment by SavageCore** [comment]
@Beelzebub2 that's a good update, I see my error in thinking with `os.walk`, thanks, will make sure I use that in my other project!

Strange I never noticed though, I've got many games! However, purely NVMe storage, maybe that's the key here.

**Comment by Beelzebub2** [comment]
@SavageCore Maybe he was a unreasonable amount of games and in a lot of different disks and at some point it must be causing an issue i've had these problems in the past when trying to use `os.walk` on different disks. anyways i thank you for your contributions im making my final project at school so i can't give too much attention to this
