### ISSUE TITLE
startup

### ISSUE THREAD

**Issue by beltra1899** [Beelzebub2/AutoBanana#3]
how do i configure it to run it when the pc starts?

**Comment by Beelzebub2** [comment]
It should add itself if it says yes on the config.ini but you must have python added to PATH i will add a function to check and do that for you

**Comment by beltra1899** [comment]
oh thanks

**Comment by Beelzebub2** [comment]
it has proven to be more difficult than what i expected simply uninstall python and install again ticking the box that says add python to path
